### ISSUE TITLE
Current temperature and geoclue2 support

### ISSUE THREAD

**Issue by Szpadel** [kotelnik/plasma-applet-redshift-control#11]
Thanks for your work! this is awesome project!
I have 2 feature requests that may help to make this plasmoid even more awesome.

First one is preview of current color temperature.
It would be nice to have it in the tolltip of the plasmoid.
(You have read current temperature using `redshift -p` or you can parse output of `redshift -v` (I think this is more elegant solution))
https://github.com/jonls/redshift/blob/master/src/redshift-gtk/statusicon.py#L176

Second it support for geoclue2 to automatically detect current location.
This would be nice feature for peope who travel frequently.

Best Regards
Piotr

**Comment by kotelnik** [comment]
Thanks a lot for your feedback and feature suggestions. I'll try to do both. As for the second I'll look into geoclue2 but I can also leverage Mozilla Location Service available in Plasma (like I do on demand in the widget settings).

**Comment by kotelnik** [comment]
Done in version 1.0.11. Please report bugs :).

I agree using "redshift -v" is more elegant and simpler solution but for now I've used the other one otherwise I'd have to create C++ extension to track stdout and therefore some users of .plasmoid only version of applet would be out of luck. I'll probably do the C++ extension eventually but for now "redshift -p" was used.

**Comment by Szpadel** [comment]
Hey

Thanks, it seems to be working fine. I test if for couple days and give feedback here in case of any problems.

Can C++ extension be made optional? So if it exists it will be used, otherwise it fallback to `redshift -p`. I can imagine some corner cases when current approach can give invalid results.

Best Regards
Piotr

**Comment by kotelnik** [comment]
Thanks! Yes, it can be made optional, I've already done that in my Weather Widget. But here it would entirely change the way redshift process is called and I don't like having 2 different codes for one thing in one plasmoid (unnecessary overhead). So I probably fork / split the project and continue the development with C++ ext. in the new one and backport fixes to the old one for users of .plasmoid version.

**Comment by Szpadel** [comment]
Hello,

Unfortunately value seems to not updating during sunset.
I think preview process isn't even spawned.

Can you check this?
I don't have any experience with debugging plasmoids, so I don't know how to check this.

Best Regards
Piotr

**Comment by kotelnik** [comment]
Hi! For me it is updating fine day->night and night->day. I can always see the tray icon become active and changing temperature value (every 10 seconds) in tooltip during the transition.

What do you mean by preview process?

**Comment by Szpadel** [comment]
Hello,

In tooltip I always have "Turned on, 6500K" with is my day temperature.
By preview process i mean executing redshift with -p parameter.
But if interval is 10s, I could miss it in noise in strace messages.

Best Regards
Piotr

**Comment by kotelnik** [comment]
Sorry, I've been quite busy lately. Thanks for the video. I can see the temp. is not updating in the widget. However I still cannot replicate the issue. Is there only one redshift process / widget active? How did you monitor the temperature in terminal on the video?

**Comment by Szpadel** [comment]
Hello

In terminal it is running watch of redshift command contains -p.
Rest of arguments I got from ps aux|grep redshift, so they are identical as in process running by the widget.
And there isn't any other running redshift processes.

Best Regards
Piotr

**Comment by kotelnik** [comment]
Thanks. I believe I used the same procedure as you while testing. Since I couldn't replicate the issue I also recorded a video of my actions so it is more clear which arguments are called and when. Hopefully it will narrow the search for the cause of this problem.

The only thing coming to my mind right now is: do you have your location set the same way in widget and in watch command?

So, here is my screencast (sorry about the flickering...):
http://sojcaci.cz/temp/github/vokoscreen-2016-03-12_15-32-00.mkv
