### ISSUE TITLE
Request: add option to preserve gamma corrections 

### ISSUE THREAD

**Issue by interj** [kotelnik/plasma-applet-redshift-control#12]
Hi, in Redshift 1.11 an option was added to take current gamma correction into account: https://github.com/jonls/redshift/releases
It's not that greatly documented, but it works just right and fixes problem of ignored color profiles. It's invoked as additional parameter passed with correction mode setting: `redshift -m randr:preserve=1`. My request is to allow plasmoid to start redshift with this parameter, because currently widget is unusable when custom screen color profiles are configured.

**Comment by kotelnik** [comment]
Thanks for pointing this out! Consider it done. Hopefully I'll have some time to work it in till the end of this week.

**Comment by kotelnik** [comment]
Done in 1.0.11. It is not perfect but should do the trick in standard scenario:
1) Apply colour profile
2) Turn on redshift (with preserve option enabled)

If you change your colour profile while redshift is running it will revert back to your previous profile. If you use mouse-wheel to manually change redshift's temperature, it will not run with preserve option because "one-shot" redshift mode is used for that and preserve would recursively preserve temperature set by previous "one shot" call.

**Comment by interj** [comment]
It works ok as far as I'm concerned. As for one-shot mode, maybe closing redshift before calling it again with changed temperature would work?

**Comment by kotelnik** [comment]
One shot mode for redshift means that you call redshift, it adjusts temperature and immediately ends. Till now your screen is adjusted. Then you can call it again. With preserve=1 would another call use this state of screen colours as the default... But maybe you know of another way how to achieve this?

**Comment by ArchangeGabriel** [comment]
@kotelnik Does this means that this applet use preserve=1 as default? Nice if so.

**Comment by kotelnik** [comment]
No, it doesn't. Preserve option needs to be set along with mode parameter. And this applet is calling redshift without the mode parameter, so that redshift can automatically decide which mode to use. But I've seen a discussion in redshift github about an intention to enable preserve=1 by default when it is properly tested. So in time, it will probably be default :).
