### ISSUE TITLE
The applet  get the wrong time.

### ISSUE THREAD

**Issue by Wuxiangdong** [kotelnik/plasma-applet-redshift-control#4]
Hello,I am happy to hear of you new applet.But It get the wrong time.(for example It'night now but the applet think it's day now.)
Maybe because of time zone.

**Comment by kotelnik** [comment]
Hi! Thanks for reporting - this is interesting issue. Since this widget only calls redshift command with some parameters I suspect that either parameters are wrong or the time zone like you said.

Just to be sure I have to ask: Did you set your location (latitude, longitude) in widget settings?
Question 2: do you have "timedatectl" command available? What does it say?

**Comment by Wuxiangdong** [comment]
Sorry,maybe I was wrong.My English is poor so I didn't know the meanning of "latitude" and "longitude"
Sorry for reporting the wrong "bug",please close it.

**Comment by kotelnik** [comment]
So after you set the location it started working? I'm glad it worked for you.

And believe me - your English is great! It must be very hard to learn English for Chinese people and vice versa. And my English could also be better :)

**Comment by Wuxiangdong** [comment]
Thank you very much :)
