### ISSUE TITLE
fr translation mistake

### ISSUE THREAD

**Issue by edouardduliege** [kotelnik/plasma-applet-redshift-control#44]
Hi,

Thanks for this nice applet. I'd like to pinpoint an issue with the french translation for the fedora 26 package. It's not "enclanché/déclanché" mais "enclenché/déclenché" and actually I would rather say something else. is this the right place to mention it? If not, where should I go?

**Comment by ArchangeGabriel** [comment]
Yes this is the right place, the lines are at https://github.com/kotelnik/plasma-applet-redshift-control/blob/master/translations/po/plasma_applet_org.kde.redshiftControl_fr.po#L126. We can make a PR once we will have decided on the proper wording, see below.

Outside of the typo (that might be acceptable, see https://fr.wiktionary.org/wiki/déclancher), the wording are worse than inaccurate: “déclenché” and “enclenché” are synonyms… The opposite of them is “désenclenché“.

And as the matter of fact, I think you cannot use them with value of adjective, because they relate to the action of turning something on or off. Not absolutely sure about that, but in any case I definitively agree those are not the best wordings in this context.

Direct translation to “Allumé” & “Éteint” isn’t working either, I think “Actif” & “Inactif” or “Activé” & “Désactivé” would work better. What are your thoughts on this? I have a preference on the latest one I think.

**Comment by edouardduliege** [comment]
Hi there,

Thanks for your answer Bruno.

>Outside of the typo (that might be acceptable, see
https://fr.wiktionary.org/wiki/déclancher)
ha interesting, thanks!

> the wording are worse than inaccurate: “déclenché” and “enclenché” are
synonyms… The opposite of them is “désenclenché“.
Agreed.

> Direct translation to “Allumé” & “Éteint” isn’t working either, I think
“Actif” & “Inactif” or “Activé” & “Désactivé” would work better. What are
your thoughts on this? I have a preference on the latest one I think.
Same.

> We can make a PR once we will have decided on the proper wording
I have no idea what it is, but if I can help you, let me know!

thanks and cheers!

Édouard

--
Édouard Duliège
edouard.duliege@gmail.com

2017-11-11 17:19 GMT+01:00 Bruno Pagani <notifications@github.com>:

**Comment by ArchangeGabriel** [comment]
PR=Pull Request, the way to suggest modifications of the code. I’ve made one: #45.

**Comment by edouardduliege** [comment]
ok I see. Thank you Bruno!

Martin, thank you for this fix and for the great work with this plasmoid ;)

Urbanely yours,

Édouard

--
Édouard Duliège
edouard.duliege@gmail.com

2017-11-13 14:59 GMT+01:00 Martin Kotelnik <notifications@github.com>:
