### ISSUE TITLE
System Tray no logner works in Plasma 5.12+

### ISSUE THREAD

**Issue by crouthamela** [kotelnik/plasma-applet-redshift-control#52]
takomora on the KDE Store: "The Redshift item in the System Tray no longer works in KDE Plasma 5.11.95 (5.12 beta). I really liked the System Tray entry feature of this, so hopefully that can be fixed in the future?"

**Comment by moconnor1234** [comment]
I actually ended up finding a fix: https://github.com/kotelnik/plasma-applet-redshift-control/issues/50 (I am the same user that posted that, this is my github account). I'm not sure what caused Redshift control plasmoid not to work after the update to 5.12 though. Anyway, thanks for mentioning the issue here.

**Comment by crouthamela** [comment]
Ah ok. Didn't see that. :)
